---
abstract: 'Perl extension for DateTime'
author:
  - 'Jim Bacon <jim@nortx.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Fiscal-Fiscal5253
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  DateTime: 0
version: 1.02
